### ISSUE TITLE
chat input not aligned correctly when using TabbarBottom component from react-navigation

### ISSUE THREAD

**Issue by achmadk** [qiscus/react-native-qiscus-sdk-js#2]
# When android keyboard is hidden
![screenshot_2017-11-16-12-49-55-068_com canirestoreactnative45](https://user-images.githubusercontent.com/8057028/32876980-ce929f60-cad1-11e7-981b-438ba7991fcb.png)
  
# When android keyboard is shown
![screenshot_2017-11-16-12-50-05-807_com canirestoreactnative45](https://user-images.githubusercontent.com/8057028/32877049-20cd7214-cad2-11e7-8d5d-d60f9ae6acc5.png)

**Comment by theredfoxfire** [comment]
We are still working really hard to extend the SDK style. Our goals is make our SDK to be more generic as component so you can make adjustment with your app style/component. Thank you for using RN Qiscus SDK.

**Comment by theredfoxfire** [comment]
hey @achmadk I've release 0.1.2 could you please update your react-native-qiscus-sdk into 0.1.2. Hopefully will solve this issue. For now I will close this, feel free to reopen when you find this issue coming up.

**Comment by achmadk** [comment]
Hi, @theredfoxfire . I have updated react-native-qiscus-sdk to 0.1.2. Unfortunately, it has more problem. Maybe `this.setState` function inside `keyboardWillHide` and `keyboardWillShow` event handler causing chat container took delay up to 5 seconds to show (or hide), so the user will have to wait to enter text (or to see chat container to the right position). Hope [this article](https://medium.freecodecamp.org/how-to-make-your-react-native-app-respond-gracefully-when-the-keyboard-pops-up-7442c1535580) can fix this issue.

**Comment by theredfoxfire** [comment]
glad to hear it's works!
