### ISSUE TITLE
chatContainer is hard to scroll after submit new text or upload new picture

### ISSUE THREAD

**Issue by achmadk** [qiscus/react-native-qiscus-sdk-js#3]
new text or picture only get 12 fps when scrolling (displayed in perf monitor)

**Comment by theredfoxfire** [comment]
We'll take investigation into this issue.

**Comment by theredfoxfire** [comment]
hey @achmadk I've release 0.1.2 could you please update your react-native-qiscus-sdk into 0.1.2. Hopefully will solve this issue. For now I will close this, feel free to reopen when you find this issue coming up.

**Comment by achmadk** [comment]
Hi, @theredfoxfire . I have updated react-native-qiscus-sdk to 0.1.2. It resolve scrolling issue, but the image uploaded from app is not shown. Here is the result.

![screenshot_2017-11-22-13-24-59-020_com canirestoreactnative45](https://user-images.githubusercontent.com/8057028/33113030-cf1dc0f2-cf88-11e7-9004-2d17660c76c1.png)

**Comment by theredfoxfire** [comment]
Ok I see your screen shoot
but it still on UI previous version, I am afraid if your cache or some thing cause this error,
can you please re check your package.js, then try to run `npm update` again
package.json sorry for typo
or you can just remove your node_module folder then rerun npm install, before you run npm install make sure your package.json already in 0.1.2 version

**Comment by theredfoxfire** [comment]
<img width="280" alt="screen shot 2017-11-22 at 13 51 43" src="https://user-images.githubusercontent.com/4158619/33113754-6038c462-cf8c-11e7-850b-6551931e9289.png">

after you update to 0.1.2  you should have new UI
